---
- name: reset and restart the network
  connection: ssh
  gather_facts: false
  hosts: ted
  tasks:
      - import_tasks: kill.yml
      - import_tasks: build.yml
      - import_tasks: reset.yml
      - import_tasks: run.yml
