---
- name: reset and restart the network
  connection: ssh
  gather_facts: false
  hosts: ted
  tasks:
      - import_tasks: run.yml
      - set_fact:
          gecko_res: "{{ gecko_res }}"

- name: save the state to state.json
  hosts: localhost
  tasks:
    - set_fact:
        all_results: "{{ dict(groups['ted'] | zip(results)) }}"
      vars:
        results: >-
            {{
              groups["ted"]
              | map("extract", hostvars)
              | map(attribute="gecko_res")
              | list
            }}
    - copy:
        content="{{ all_results }}"
        dest=./state.json
