---
- import_playbook: helper/env.yml
- import_playbook: helper/load_state.yml

- hosts: localhost
  tasks:
      - file:
          path: "{{ work_dir }}"
          state: directory
      - name: check the state status
        fail: msg="nodes are already started"
        when: last_state['status']  == "started"

- name: reset and restart the network
  hosts: "{{ host_group | default('all') }}"
  tasks:
      - import_tasks: helper/run.yml
- hosts: localhost
  tasks:
      - set_fact:
          cur_state: "{{ last_state | combine({'status': 'started'}) }}"
- import_playbook: helper/update_spawn_state.yml
- import_playbook: helper/save_state.yml
