---
- import_playbook: helper/env.yml
- import_playbook: helper/load_state.yml

- hosts: localhost
  tasks:
    - file:
        path: "{{ (work_dir, 'remote') | path_join }}"
        state: directory

- name: fetch files from the remote
  hosts: "{{ host_group | default('all') }}"
  tasks:
    - import_tasks: helper/fetch.yml
      vars:
        work_dir: "{{ hostvars['localhost']['work_dir'] }}"
